name: Build

on:
  push:
    branches:
      - main
      - test

jobs:
  Linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install ninja-build
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build
        run: ninja
